### ISSUE TITLE
Set up a voting mechanism for the idea pitch

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#117]
e.g.
http://govote.at/ / https://www.menti.com/ or similar

**Comment by EJ-Van** [comment]
I did some asking around about this. The tool Poll Everywhere (https://www.polleverywhere.com/) was suggested. 

There is a free plan for non-profits, but this only allows 25 responses, which is probably not enough, hey? A plan that allows up to 100 responses is $79 per month. But, you can just use it for one month and then change the membership plan to the free version. That plan also allows you to customize URLs. From the site:

`If you only plan to use Poll Everywhere for a single poll on a single day, you still need to subscribe to a monthly plan, even if it is only for one month. You will be charged the monthly fee for your first month, even if you downgrade to the Free plan before the month is over.`

I looked at the mentimeter pricing options, too (Professional: https://www.mentimeter.com/plans and Education: https://www.mentimeter.com/plans/education). It doesn't look like the free options will work for us because those plans don't let you export results. The $7.99 per month option looks like it would work for us. Billing is annual, so I assume that means $7.99 x 12 months. If we count as educational use, then it is $4.99 per month. 

There are also conference plans, but these seem to be more than we need: https://www.mentimeter.com/plans/conference
