### ISSUE TITLE
Contact neuroscience labs for potential Journal club about OA issues for this community

### ISSUE THREAD

**Issue by natesjacobs** [force11/force2017#118]
would be mid-day the day before the conference (Tuesday)

**Comment by bmkramer** [comment]
Hi Nate, 

Did you guys discuss/decide on this timeframe on the call tonight? If not, I have some thoughts about it :-) 

kind regards, Bianca

**Comment by natesjacobs** [comment]
No I wasn't able to be on the call because it was during work hours for me.  I'm actually going to close this issue and we can reopen when we start grouping issues as you suggested in email

**Comment by bmkramer** [comment]
related to #24 Think about how to involve researchers

**Comment by bmkramer** [comment]
I like the idea of just starting on this by multiple people contacting a few research lab and trying to arrange something (as Nate put it in an email:

"hey I'm a neurophysiologist in town for FORCE17, and was wondering if I could stop in for a journal club and discuss OA related issues in this field."  I think it's important that it's about discussing issues, not necessarily about getting them to come to the conference.  However, simply mentioning the conference name right as we've opened registration may prompt some traffic incidjentally"

I do wonder though if and how we can broaden the scope of this and try and involve more conference participants. Having it on the day before the conference will limit the number of Force11-people participating (especially because people already in town are probably there for one of the satellites) and potentially even realizing this went on as an activity. It would be nice to have at least a reporting back activity then later on in the conference proper? 

One other option that I've been considering is to organize this as a session or unconference activity during the conference itself, with us scouting for interested research groups beforehand and announcing the opportunity to participate during the (un)conference (making sure we have at least a number of people committed beforehand so as not to let down interested research groups, of course).

Both approaches have their pros and cons, of course. Let's compare & contrast ;-) 

(Oh, and we could tailor the approach to research groups to include subjects beyond OA)

**Comment by natesjacobs** [comment]
one other option to throw in the mix that I thought of when reading Bianca's comment. We could have these be "grab a beer with us"  get togethers after the conference each day. but maybe that's too casual...

if they came to the session during the conference, would they have to pay and register?

**Comment by bmkramer** [comment]
I like the idea of 'grab a beer with us', too - maybe in combination with an outreach session on one day in the afternoon, followed by such an invitation. Don't know if that would require a separate sponsor, though :-)

My idea/option to organize this as a session would still involve 'us' going to the various research groups, btw. So that would not require a decision on payment/registration.

**Comment by bmkramer** [comment]
I would like to propose switching the label from 'social' to 'content and logistics' for this one. 

Also, I think that it can be a mid- rather than early planning activity. Shall we discuss this at the call next week (Aug 3)?

**Comment by bmkramer** [comment]
Now on programme as session 100 - will be further organized as session
