### ISSUE TITLE
Shall we go for a "Bring your own badge" system?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#122]
Event badges serve two main purposes:

1. identify the wearer to other participants
1. signal to everyone that the wearer's participation is OK with the event organizers

Presumably, most Force 2017 participants already have old badges or similar to identify themselves to other participants, so why not have them bring their own badge? That might also help showcase the diversity of events people have previously attended, and could act as a conversation starter.

To address 2 (e.g. to see whether an attendee has actually paid their Force 2017 dues), we could add stickers to the participants' badges.

**Comment by bmkramer** [comment]
+1 !

**Comment by kamc** [comment]
I somewhat like this idea, as a simple and fun conversation starter, but I do have two concerns with it.

The first is maybe not a big deal at all, but not everyone saves all their old badges. 

My larger concern is that it creates a bit of a gap between participants that are new or just getting started. Those folks that are just entering this sphere are the ones that are most likely to already wonder/worry if there really is a place for them. If they are the only ones with badges made for this conference, that may amplify, rather than ease, those concerns.
