### ISSUE TITLE
Think of a consistent system for taking notes during each session

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#135]
Using something collaborative like Etherpads or Google docs works only at conference scale if really supported on the part of the organizers.

On the other hand, getting this right might 
- produce a documentation of the event that is more useful than tweets alone, and earlier than classical reporting
- illustrate in a simple way the overall change of culture that we want to address with the conference.

**Comment by Daniel-Mietchen** [comment]
An example of an event where taking notes via Etherpads worked nicely for the most part:
https://meta.wikimedia.org/wiki/WikiCite_2017/Program

**Comment by bmkramer** [comment]
@Daniel-Mietchen One tool for creating a number of Google Docs based on a template, with inserted data from a spreadsheet, is AutoCrat, a GSheets add-on. I'll try it out to see if it's useful. Haven't found something similar for etherpad yet. 

(you asked this somewhere else but can't find that anymore - please move accordingly if needed)

**Comment by Daniel-Mietchen** [comment]
Sounds good - I asked about this at
https://twitter.com/EvoMRI/status/905902074361196544
and
https://groups.google.com/forum/#!topic/etherpad-lite-dev/v4D821kV8Ls .

**Comment by bmkramer** [comment]
OK, I set up a test with AutoCrat and GDocs, works like a charm! 

See documents in this folder:
https://drive.google.com/drive/folders/0B-T8WcfMD1YsME9RQlYwVkduTW8

- template doc
- spreadsheet with data + AutoCrat add-on
- 3 resulting docs with inserted data  (automatically generated)

This is easily set up and completely customizable.

**Comment by kamel2017** [comment]
*Hi Bianca and Daniel,*


*Excellent work that will make good material for  Force2017. *
*Kamel*

**Comment by kamel2017** [comment]
How to create Google Docs or PDFs using Autocrat
https://www.youtube.com/watch?v=SkpY2ODnncA    ,

Best regards

**Comment by dcht00** [comment]
Dear organizing committee of FORCE.

I noticed @Daniel-Mietchen 's post on the Etherpad mailing list post on this topic. Here's a slightly modified version of my response to him that he encouraged me to post in this thread. I hope we can find a way to work together!

---------------------------

In terms of your ideas, as far as I understand, you'd like to have:
* an already running public Etherpad instance
* that can facilitate a larger number of participants (perhaps 100+) on >100 sessions
* ... these set up the pads in a programmatic way: name them + seed initial content from some sort of a sessions manifest file / spreadsheet

I've been building on top of the Etherpad system for a while now, as part of the Totalism.org system. I've developed "E2H", which **regenerates the pads as presentable HTML sites** (and perhaps other formats). It also adds features such as internal (and cross-pod) **links to other pods, text-to-graph generation, auto-TOC**, etc. You can find some documentation about this here: http://totalism.org/e2h.php?_=E2H (You will be able to find the "Edit site" button on the bottom of the page, to illustrate the concept).

I also believe E2H connects to the conference's focal point, and so does some of my other work and interests in the direction of "hypertheory"!

Anyway - in terms of a larger number of participants, here's one example of one larger multi-participant instance we did in December:
http://pad.totalism.org/p/33c3-hacker-workflows/timeslider#3861
(press play and wait ~10 seconds).
I think it went up to something over 30 people - but it did not deteriorate in any way. 

Since I have several sites running on the Etherpad service for years now, I like to think the whole system has been made pretty **stable and self correcting**.
Another thing I have been practising, with the desert-based Totalism.org, is **intranet (localnet) etherpad sessions**. In the context of conferences - wifis can be flaky, especially with regards to (outer) internet uplink, especially in such a realtime application as Etherpads. **Having at least a backup, if not a main, localnet system to save your skin is a privilege.**

The case you are describing would be an welcome direction for the development of E2H. Covering quality large, socially engaged, highly participatory events, to **produce quality content that outlives the moment in which it's produced**, and **assist the process with my own domain knowledge** - is absolutely an interest.

So if you are interested in this collaboration, and we can find the means to do so, I would be happy to jump onboard.

-----------------------------------------

**Comment by dcht00** [comment]
I see you are now also considering using Google Docs for collaborative document/note authoring.
While this might be simpler to pull off, here are a few **downsides of using Docs** that I can think of:
- it's a proprietary, corporate, closed-source solution. This is as I understand not favored by your principles (as outlined in https://github.com/force11/Force11-DecisionTrees )
- no chance of localnet setup (=running the notes direct on the local network, if the conference internet fails)
- by choosing a proprietary solution, you are missing a chance to take a lead that other conferences can follow, that would fit your purpose
- as it's closed source, you cannot creatively influence the development of the platform! I would argue that even the potential to do so can animate the conference participants about the tools they use to collaboratively think and scheme, and set more ambitions for next times. You simply do not have this "creative medium" by choosing the proprietary Google Docs.

In addition, the system I authored and am proposing, **E2H, has some advantages to produce lasting results of the sessions**:
* stronger inter-document linking, necessary to create indexes, etc
* stronger possibility of presenting the content (HTML sites are generated separate from the collaborative document, and can be hosted on your domain, ...)
* simpler structuring of the messy collaborative text (by using the automatic table of contents from simple styles)
* simple text-to-graph capability, which would give another creative dimension I noticed you are already using (with the "decision trees" github repo). This would upgrade on that capability.
* lastly, Etherpad is less bloated that Google Docs - loads faster, looks cleaner, etc. It's a stylistic preference, but it feels better for authoring notes (in contrast to authoring "Documents" for print).

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#8
