### ISSUE TITLE
Think about how to involve researchers

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#24]
Perhaps as part of the main program, through satellite events or dedicated outreach.

**Comment by bmkramer** [comment]
Main points from previous discussion within programme committee, mostly over email (please add any omissions) @Daniel-Mietchen @mellybelly @mfenner @pitviper6  @natesjacobs Heather Staines Katie Chapman 

- Directly relates to the closing remarks of Phil Bourne last year in Portland, about the need to involve more researchers in Force11: "Can you get them to come to these sort of things? If not, what can you do to engage them?" 

- Possibilities: 
  1.  reaching out to local organizations (e.g. Wikimedia, citizen science organizations, etc.) to co-organize sessions, and advertise and open these up (e.g. session-by-session) to the local research community
  2. dedicate part of a day (say, 2 consecutive sessions) to an outreach-and-connect activity. This could involve getting researchers and Force11 members together in small groups, e.g. over coffee at local institutions, and exchange thoughts on some of the topics we’ll be discussing at Force2017 and how they relate to the daily practice of researchers
  3. ' journal club' style meetings - target small clusters of researchers (1-3 labs) to discuss scholcomm issues in their conference room on their floor in their building. We would ask to use conference room and hold a meeting and invite whoever was interested. 

ii. and iii. capitalize on the notion (based on experiences at Force2016) that **perhaps Force11 needs to go where these people are instead of expecting them to come to us**. It could also lead to a follow-up activity at Force2017 itself to discuss commonalities in approaches versus what is really very domain specific. 

- What would be the motivation for researchers to engage in these discussions with the Force community?  
  - frustration with the current system
  - uncertainty on how to comply with imposed sharing mandates
  - learning about possibilities (practices, platforms, tools) to make their workflow more efficient, open and reproducible
  - the opportunity to hear from and discuss with funders, publishers, tool makers when they come to their own institutions (i.e. low investment)
  - the opportunity to share their frustration with current mandates/proposals/solutions, or: why what we are thinking about might not work for them. Having their voices heard. 
  - hearing from others at the same institution (perhaps from different disciplines) about how they might struggle with similar issues, and what solutions they might see/use. 

- Decide to do this as **part of the conference itself** (potentially taking away time from face-to-face community building within Force11 itself) or set up for some time  **on the Tuesday prior to the conference,** or even on the Monday. 

- Liaise with open access person local to the area/institutions (e.g. Fachreferenten), as a means to open those dialogs in connection with OA Week efforts. [NB without limiting to OA only - BK]

- Feedback from those meetings could be presented and built upon within the Force11 community during the conference. Perhaps it would even open doors for individuals from those institutions, organizations, etc to feel welcomed and desire to come and join in at the conference as well.

**Comment by bmkramer** [comment]
And proposal for next steps:

- Decide on whether we want to pursue / realize this
  - as journal club idea? yes/no
  - as pre-conference activity or allot sessions during the conference? 
<br>

- If answer is yes and choices are made as to format and timing:
  - formulate concrete steps to take
  - involve outreach committee
