### ISSUE TITLE
Plan lunch talks/ demos

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#32]
informal, such that people can have lunch in parallel.

some inspiration in the "open fashion" demo at http://events7.mediasite.com/Mediasite/Catalog/catalogs/2017assembly .

**Comment by kamc** [comment]
Both with this and with our social event(s) #14 , should we do like was decided with #10 #11 and #12 and simply create a doc, send it out to everyone, and have each of us list favorite ideas for each?

**Comment by Daniel-Mietchen** [comment]
Sounds reasonable.

**Comment by kamc** [comment]
I will try to put that together for next week and we can start on filling it in with ideas as soon as we have wrapped up that process for the keynotes.

**Comment by kamc** [comment]
Here is the doc so far. I would rather hold off on diversity type comments until after an initial vote to keep as open minded as possible as long as we can, but I can switch that if need be. Also, how many times do we have each person vote? My thought would be three times (per round if it takes more than one voting round) since there are three lunches. I will add this to the Google Drive folder and send it out when we are ready to gather these ideas. Perhaps next week?

https://docs.google.com/spreadsheets/d/1MF7kQrXmMlIRVFaycMbchcy_yk7oawmS6qZ2UZ7aW9E/edit?usp=sharing

**Comment by kamc** [comment]
We may be too late in the game to approach this in the way that we originally suggested, but what should we do at this point in time? Having some sort of something interesting during the lunch breaks sounds like a lovely thing, but we are limited in terms of time to prepare something at this point and need to act quickly if we are going to try to do anything in that time.

**Comment by kamc** [comment]
If we are not going to add anything of interest during the lunch break time, we could shorten that time by a little bit and use the extra time to spread between each session  ( #44 ) to allow for changing of rooms. Just a possibility.

**Comment by bmkramer** [comment]
Yes, I think that would be a great way to go about this. Also given that we
have so many things going on in the programme itself (many parallel
sessions etc), I think having lunch for, well, lunch, networking,
socializing and recharging might be enough.



2017-09-21 22:15 GMT+02:00 kamc <notifications@github.com>:

**Comment by kamc** [comment]
I think I agree with that. I liked the idea of incorporating something very different during lunch, but this is going to be a packed conference and down time might be extremely important, just for downtime.
