### ISSUE TITLE
Help attendees organize themselves

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#48]
- e.g. for social (#14), idea challenge (#23), unconference (#22), breaks (#44), posters (#42), demos (#43), satellites (#45).

Could be something online like a new GitHub ticket with a [meetup label](https://github.com/force11/force2017/labels/meetup) or a dedicated Twitter hashtag or something involving the registration desk

**Comment by kamc** [comment]
Does the meeting planning company provide any sort of attendee interface to see the conference schedule online or via an app or anything? I have seen that before and that would work to have people sign up that way and then all attendees would have the information. Otherwise, what mechanisms do we have at our disposal to share those prospects? We need the ability to get out that sort of information in essentially real time and to as many people as possible. A white board outside the main conference room can work, but something that we can get into their hands would be nice. Twitter seems possible I suppose, though I've never seen that done. Would we simply use one hashtag for all unconferencing? I think GitHub would eliminate too many people possibly.

**Comment by bmkramer** [comment]
I think last year [Sched](https://sched.com/) was used, which I've seen used at other conferences as well. I like it as an online mobile solution, but I'm not sure how easy it is to update scheduling info on the fly. 

Maybe @mellybelly can add to this?

**Comment by mellybelly** [comment]
last year we used sched for the workshops because we needed to be able to better manage content than we could in the Force2016 Drupal site. But we didn't have it for the whole conference. Personally I quite liked Sched and would be happy to have this for the whole conference. Most conferences I go to have a phone app these days and it would be very nice to have this for Force2017.

-1 to github, needs to be more social app oriented. There are also other tools that are fun for attendees to find eachother, we have done this at VIVO before too, @vioil probably knows what was used but it was really cool to capture expertise and activities of attendees

**Comment by kamc** [comment]
Thank you both. I'm looking at sched now and wishing it had been available for the whole conference last year. So far, I'm liking what I'm seeing.

**Comment by kamc** [comment]
This may be an odd question, but what exactly does the meeting planning company do? What do those fees we heard about in the call cover? I'm just trying to get a better feel for where they fill and what we need to fill in other ways.

**Comment by kamc** [comment]
Some (not all) comments from the email string about this:

From Sched: "Sched is designed specifically to handle changes on the fly. All of the different versions of your schedule (web, mobile web, embedded version, calendar sync, native app) are constantly in the sync so that they will all update when you make any changes. Whether you're adding sessions, canceling them, changing speakers, times, venues, etc...everything stays in sync. You can make the change right in the control panel and it gets pushed everywhere immediately.

If you have someone adding unconferencing sessions as they are proposed/approved, they'll be launched and added to the schedule immediately."

Violeta: "In Sched we can collect all sorts of data: attendance per session, room assignment, attendees list, export session details either in csv or pdf for people that like paper schedules, there is eventbrite sync if that system is used for registration, you can email people from there directly, and so much more."

Stephanie: "Hi Katie – I don’t think I ever answered this one.  Martin and I are the contacts for Copernicus.  I looked through their agreement and all it says about abstracts is this:

“The Licensee hosts the website, facilitates the abstract submissions and selection, generates the online programme, and produces a master PDF file of the programme”

Not very helpful! 

Maybe we should create a list of questions for Copernicus and I will send them on and ask them."

**Comment by kamc** [comment]
If we have questions for Copernicus, it would be good to get those to them ASAP I would think.

**Comment by kamc** [comment]
Also a comment from the "Lessons Learned" document from last year:

"The redesign of the website looks really good and we appreciated how helpful Josh was with our requests. The display of the agenda was nice and easy to read. However, we would strongly recommend the use a conference management system for workshop and session submissions and not use the Drupal site in future years. "

**Comment by vioil** [comment]
We won't use Sched , instead we will use the live google spreadsheet that Copernicus will post on the website
