### ISSUE TITLE
Aim for diversity and inclusivity

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#50]
in terms of attendees, presenters, fellows, topics, activities
but also venue, website, food etc.

Review existing tickets with that in mind.

**Comment by Daniel-Mietchen** [comment]
Some dimensions of diversity
- Research background
- Geographical background
- Gender
- Age
- Disabilities
- Linguistic background
- Technical background
- Artistic background

**Comment by mellybelly** [comment]
also age/career status/role

**Comment by Daniel-Mietchen** [comment]
Just added the lightning talks label because lightning talks can help showcase the diversity of the community, the issues worked on and the approaches taken etc.

**Comment by Daniel-Mietchen** [comment]
There is a diversity checklist that came out of an analysis of OpenCon:
- https://sparcopen.github.io/opencon-dei-report/checklist.html

**Comment by danielskatz** [comment]
faith or lack thereof

**Comment by jenniferfsmith** [comment]
We can't talk about diversity and inclusion without also addressing race and ethnicity.  These are issues that go far beyond what is captured by geographic origin and linguistic background.

Also, Force11 should strive to ensure that its leadership team and planning committees reflect the diversity of the scholars who they would seek to have attend.  If people of color, people from under-represented communities, and people outside of Europe and English-speaking North America are not currently serving in leadership roles, they should be recruited because their perspectives and contributions are valuable and important.

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#11
