### ISSUE TITLE
Create Code of conduct

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#51]
Can probably be taken from https://www.force11.org/meetings/force2016/code-conduct right away, perhaps with some slight adaptations.

Could perhaps be part of the submission fineprint (#2).

See also #50.

**Comment by sthagstrom** [comment]
Hi Daniel - I did not realize you wanted the Code of Conduct changed.  This is the Code of Conduct that has beeen adopted for ALL Force11 events so we should not alter.  The only change for this year is one of the COC members has resigned from the committee.  I sent the correction to Copernicus to include on the website.

**Comment by Daniel-Mietchen** [comment]
I had no concrete intention to change that text, but wanted to leave that option open in case we find something that would need/ benefit from changing. I just re-read it and did not find anything in need of change.

I had also not been aware of this code's official status - perhaps that should be made clearer by moving/ copying/ redirecting the text to 
https://www.force11.org/meetings/code-conduct ? Can you link to the decision to make it official?

**Comment by vioil** [comment]
We should create an stable page on the Force11 site for the CoC since it is now officially accepted.
I see few pages: https://www.force11.org/meetings/force2016/code-conduct
And this one: https://www.force11.org/fsci/event-code-conduct

@sthagstrom can we ask Josh to do that please?

**Comment by sthagstrom** [comment]
Absolutely. No need for Josh on this one. I can do this later today I just need  to attach it to one of the menu items. I am thinking under community? Or events?  Where do you think it should go?

Thanks

Sent from my iPhone

On Jun 5, 2017, at 12:45 PM, Violeta Ilik <notifications@github.com<mailto:notifications@github.com>> wrote:


We should create an stable page on the Force11 site for the CoC since it is now officially accepted.
I see few pages: https://www.force11.org/meetings/force2016/code-conduct
And this one: https://www.force11.org/fsci/event-code-conduct

@sthagstrom<https://github.com/sthagstrom> can we ask Josh to do that please?

**Comment by bmkramer** [comment]
There is a COC page for Force2017 already, too!

http://www.force2017.org/information/code_of_conduct.html


2017-06-05 21:50 GMT+02:00 sthagstrom <notifications@github.com>:

> Absolutely. No need for Josh on this one. I can do this later today I just
> need to attach it to one of the menu items. I am thinking under community?
> Or events? Where do you think it should go?
>
> Thanks
>
> Sent from my iPhone
>
> On Jun 5, 2017, at 12:45 PM, Violeta Ilik <notifications@github.com<

**Comment by vioil** [comment]
good, I'll close the ticket

**Comment by vioil** [comment]
@sthagstrom we should link to it from the main Force11 site. you are correct, it can be under community.

**Comment by mfenner** [comment]
can we close this issue? As code of conduct is on Force2017 website.

**Comment by sthagstrom** [comment]
Yes, but I don’t know how so you will have to do this for me.  Thanks - Steph
