### ISSUE TITLE
Agenda for task planning sprint on June 6

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#72]
Another task planning sprint will be held tomorrow at 4:00-5:30pm on June 6 (i.e. tomorrow)
Focus: 
- Continue to review and refine what is already there and what is missing
- Assign responsibilities to existing issues
- Bundle issues into milestones

**Comment by kamc** [comment]
A few tickets on my mind include:

#42 (Plan poster session)
#32 (Plan lunch talks/demos)
#14 (Define elements of social program)
#48 (Help attendees organize themselves)
Also, going over the schedule one more time together on that call may be helpful?

[edited to add titles of linked issues - BK]

**Comment by kamc** [comment]
In reviewing the lessons learned document about last year, there are a few things that I am not sure we are planning on or not or if they are already in a ticket or not, but wanted to bring them up to quickly go over perhaps. They can then be made into tickets, the tickets worked on, or set aside as not relevant to this year.

- Graphic notetakers were enjoyed by all

- Persons applying for stage sessions, poster sessions, and travel funding should not receive multiple notifications spread out over a period of time. (Once they receive the first, they ask about the others). This would be made easier with a conference management system.

- Notify submissions before updating the online agenda.

- We had a lot of really great invited speakers for the sessions, however it wasn’t clear to them that they needed to register and pay for the conference. Session chairs should inform their speakers that they need to register and pay for the conference, OR we should pay for them. There were a lot of assumptions that they would not need to pay. (This might be VERY important to address before we send out the to make it clear that speakers will be expected to get themselves there and register. Could there be some possibility of inviting them to apply as Fellows?)

- Better records and tracking for our sponsors. We need to know who the contacts are and who the FORCE-friendly people are at each company or organization. We shouldn’t start with a clean slate every year. It was hard to get engagement of some of the key players due to not having the personal contacts. (May not relate to us, but what IS our role in this aspect? How are we supposed to be helping or working with the Sponsorship Committee?)

- (Also what is our role with publicity? Here are two related comments for instance.) 1. Need to have a well defined publicity plan at the beginning of the conference planning and a point person to move this forward. Lack of an all-member listserv made it hard to communicate. 2. The use of a assigned blogger really helped capture the planning and excitement up until the conference and we got a lot of positive feedback.

- Too many volunteers, too early, with little vetting or accountability. They mean well when they sign-up to volunteer for chair and committee duties, but need to check-in with *real* status reports. They also need to let others know when they need support or ideas or clarification or relief.  Too many conference calls for too long.  By the end the enthusiasm had all but gone away and it was just a very few people doing all the work. Not sure the lesson here but we need to somehow ensure more active engagement of those that volunteer otherwise too few people are left holding the bag. Perhaps free registration for a certain effort? About ⅓ committees/chairs failed to really engage adequately. 

- If we are going to try something new [referring to new tech] -- especially if it involves attendees or submissions -- we need to be trying it out and writing instructions for them weeks in advance. The first pull from Figshare (4 days before conference) did not go smoothly and some registrants are not tagging their content correctly. Also 4 days before the conference, we have an online voting app for Pitch It that nobody on the planning committee or logistics committee has seen or tried yet. (note: the voting ultimately worked very well!). openVIVO amazingly went live and also worked out well, but it was so close to the conference time that it was hard to get tested in time. (This brings to mind #48 right off the top of my head, but we need to address each of these needs and how we plan to meet them early enough to feel well prepared and tested.)

- Need seating in the venue for people who are not in the session. We lost a lot of people to the local cafes instead of them mingling together in the facility. There were some complaints about lack of seating at lunch time. (Relates to a few different issues like #32 and #14  and others. Should this just become it's own issue and connect to other related issues? I'm still trying to get the rhythm for GitHub.)

It would be good to review together - possibly BEFORE the submission system goes live or the call goes out - the section of the document on "conference content" (starting about page 5) and the section on "general recommendations for next conference" (on the last page basically).


I can try to find all the right tickets for this information or create what we don't already have tickets for, but just thought a quick review might be able to clear some of this and not create extra work or miss something important. I am fine if we do not so this as a group, but thought it might help. :)

**Comment by bmkramer** [comment]
One other issue that I would like to see prioritized (and happy to be assigned responsibility for as issue) is:

#24 (Think about how to involve researchers) (cross-fertilization with the local research community)
(extend to other local communities as needed/feasible) 

As reflected in the ticket, we already made some strides in thinking about ways to do this, and I'd like to take this further. I also think it requires enough lead time, which I why I'd like to include it as prioritization at this time. 

regards, Bianca

**Comment by Daniel-Mietchen** [comment]
Thanks both. I have started the meeting by assigning #24 to Bianca. Will try to get at the other more complex points as well.

**Comment by Daniel-Mietchen** [comment]
The meeting just ended.
We looked at all of the above and have created a number of additional tickets:
#76, #77, #78, #79, #80, #81, #82, #83.
