### ISSUE TITLE
Define number of keynotes, choose keynotes

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#8]
the [current arrangement](https://docs.google.com/spreadsheets/d/12KegT8b4B8gKci-8GOMFSK6aK8P0vyLuvVybdFfhhpA/edit#gid=0) suggests three:
- in the morning of day 1
- around noon on day 2
- at the end of day 3

**Comment by bmkramer** [comment]
Action items from May 11 call (#41)

- Generate spreadsheet for keynote suggestions (based on 2016, with suggestions added). 
- add suggestions (and complete info) until **end of this week**
- committee members to vote **next week until Wednesday**, make shortlist during next call

NB Due to personal nature, the voting sheet will be private to programme committee members. 

But anyone can add suggestions for keynote speakers in the comments here!

**Comment by mfenner** [comment]
Keynote speakers have been confirmed and listed on website at https://www.force2017.org/program/keynote_speakers.html.
