### ISSUE TITLE
two websites for Force2017 - combine into one?

### ISSUE THREAD

**Issue by nicolevasilevsky** [force11/force2017#89]
Currently there are two websites for force2017:
https://www.force11.org/meetings/force2017
http://www.force2017.org/
Could these be combined into one page?

**Comment by natesjacobs** [comment]
These should absolutely be combined!  

This will require 1) removing all redundant and unnecessary info from the "stub" page on the main F11 site, and just providing a brief description (2 sentences) and a link to the conference website, and 2) on the actual conference page (force2017.org), making sure as much of the information as possible is on that site itself, rather than having to link back to main F11 which it does in a couple places and sort of breaks the flow.  

If people agree i can operationalize this into a few separate tickets

**Comment by nicolevasilevsky** [comment]
I agree!
