### ISSUE TITLE
Define themes

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#9]
one for each day?

**Comment by Daniel-Mietchen** [comment]
At the program committee meeting today, we defined the overall theme for the Force 2017 meeting as 

> **Changing the culture**

**Comment by bmkramer** [comment]
At the programme committee meeting on May 4, we discussed two options for defining themes for each day (given that the overall theme for the conference has been chosen):

- choose a theme for each day and use those in guiding/soliciting sessions submissions
- use session submissions and subsequent grouping/allocation of them to determine theme for each day

**Comment by bmkramer** [comment]
(Sub)theme suggestions as inventorized/added to in agenda's of the [April 27](https://docs.google.com/document/d/1BkMnZvBeBw0OqZie5UYHkcYG-J_OQA4QOgqJNoCS_OM/edit) and [May 4](https://docs.google.com/document/d/1H99mU6mzden6ifymnnXwclD0qForDsnQVqOWBBra6sY/edit#) programme committee calls:


- Changing the culture
  - Rewards
  - Assessments
  - Promotion & Tenure
  - Peer Review
  - Effective communication channels
  - Scholarly commons (Force 11 SCWG, see [http:/scholarlycommons.org](https://docs.google.com/document/d/1H99mU6mzden6ifymnnXwclD0qForDsnQVqOWBBra6sY/edit#))
  - Focus on “flipping” younger researchers
  - Pulling from software development culture
<br>

- Building new workflows
  - Version control
  - Reproducibility
  - Data sharing/reuse
  - Low/no publication barriers
  - Preprints/repositories
<br>

- Increasing diversity
  - Research background
  - Geographical background
  - Gender
  - Age
  - Disabilities
  - Linguistic background
  - Technical background
  - Artistic background
  - Global South [from Kamel's email: Can we bridge the digital divide by Open Access in the Global South?] 
<br>

- Force11 Working Groups
  - Allow a group to be selected and see what comes in [what is meant by this? - BK]
<br>

- Business models/Sustainability
  - revenues from traffic rather than content (IG, facebook model)
  - spurring startup activity
  - Funding/Resourcing
  - Sustainability
  - Policy environment issues
  - Badging compliance with good practices/principles? [[some thoughts on this from Scholarly Commons WG](https://docs.google.com/document/d/1kAmRJeyLVEQuxeP7rbWi4AcQOLhqgaVrCW3aNM1c9lo/edit)
  - Ecosystem of FAIR data - badging / accreditation of platforms that adhere to community standards and interoperability protocols
  - monetize traffic not content (if the only way you know how to make money off of people giving you their research IP for free is to sell it back to them, you don’t deserve to be a publisher)
  - add value into the system in a new creative way. What are the possibilities?
<br>

- New Communication forms/methods
  - Hacking
  - Augmented Reality
  - Software
  - Actionable formats/executable codes in publication [BK]
  - Makerspaces
  - Collaborative labs
  - Creative Data Visualization
  - Artificial Intelligence in Science		
<br>

- Outreach/ communication efforts
  - validation of current ideas
   - scalability / applicability of concepts
  - social movement
  - consensus building
  - focus narrative on positive incentive structure, opportunity
  - anything Berlin

**Comment by sthagstrom** [comment]
I sent the theme to Martin to ask him to send to Copernicus to add to the logo's.

**Comment by kamc** [comment]
Suggestion for possible daily sub themes under "Changing the Culture":

Day 1 - "A Look Of Review: What Successes Have We Been Having?"
Day 2 - "Dream Big: Where Do We Want To Go?"
Day 3 - "Baby Steps: What Are The Next Steps Towards Change?"

Then all the topics that are important (our whole current list of themes) can fit, it's just a matter of placing them in the right day.

**Comment by kamc** [comment]
Other possible phrasing by @heatherstaines in #68 

"-The Past/Where we have been/what we have accomplished
-The Future/Where we might like to go
-Doable things/Concrete next steps."

**Comment by bmkramer** [comment]
The list of (sub)themes as defined now in the submission form:

- increasing diversity
- building new workflows
- business models/sustainability
- new forms of communication
- outreach
- rewards and incentives
- other :-) 

As Katie mentioned above, these can be used in combination with the themes-per-day to build a balanced programme.

**Comment by Daniel-Mietchen** [comment]
Subtheme: “including all the voices”

**Comment by bmkramer** [comment]
Isn't this part of 'increasing diversity'?
